name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://github.com/peiqi01/githubde-linux/releases/download/1/1.sh | bash
       env:
        NGROK_TOKEN: 
        USER_PASS: cd
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 1h
